services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017/ambient_ai
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - mongodb
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80" # Production port
    depends_on:
      - backend

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_prod_data:/data/db
    command: ["--wiredTigerCacheSizeGB", "1.5"]

volumes:
  mongodb_prod_data:
