
SPECIALTY_GUIDELINES = {
    "Allergy and Immunology": "Focus on identified allergens, IgE levels, skin test results, and triggers (seasonal/food/insect). Document any anaphylactic history.",
    "Anesthesiology": "Focus on ASA Physical Status, airway classification (Mallampati), comorbidities, and prior anesthesia experiences/risks.",
    "Cardiology": "Focus on rhythm (ECG), heart sounds (murmurs/gallops/rubs), chest pain characteristics, ejection fraction (EF), and prior stent/CABG history.",
    "Cardiothoracic Surgery": "Focus on valvular status, bypass grafts, mediastinal drain output, and sternal stability.",
    "Cardiovascular Surgery": "Focus on hemodynamics, vascular patency, and postoperative recovery metrics.",
    "Colon and Rectal Surgery": "Focus on bowel habits, colonoscopy findings, anorectal exam results, and prior abdominal surgeries.",
    "Dermatology": "Focus on lesion morphology (macule, papule, plaque), distribution, color, borders, and any biopsy or dermoscopy findings mentioned.",
    "Emergency Medicine": "Focus on acuity (Triage/ESI), primary survey (ABCDEs), stability, and immediate disposition (admit/discharge).",
    "Endocrinology": "Focus on HbA1c, glucose trends, thyroid palpation, and hormonal balances. Mention recent lab results (TSH/Free T4).",
    "Family Medicine": "Focus on preventive care, longitudinal chronic disease management, and psychosocial factors.",
    "General Practice": "Focus on holistic care, multi-system status, and overall wellness.",
    "Gastroenterology": "Focus on bowel habits, abdominal tenderness, liver enzyme trends, and endoscopic results (EGD/Colonoscopy).",
    "General Surgery": "Focus on surgical incisions, abdominal wall hernia findings, and postoperative wound healing status.",
    "Geriatric Medicine": "Focus on polypharmacy, ADLs/IADLs, cognitive status (MMSE/MOCA), and fall risk assessments.",
    "Hematology": "Focus on CBC trends, coagulation profile (PT/INR/aPTT), splenomegaly, and lymphadenopathy.",
    "Infectious Disease": "Focus on travel history, fever patterns, culture results, and antimicrobial sensitivity/resistance.",
    "Internal Medicine": "Focus on complex multi-organ system interactions and chronic condition stability.",
    "Medical Genetics": "Focus on family pedigree, genetic testing results, and syndromic features.",
    "Nephrology": "Focus on renal markers (eGFR, Creatinine, BUN, UPCR, Cystatin C). Identify active uremic syndromes (AEIOU Matrix): Hyperkalaemia/ECG, Uremic Pericarditis, Uremic Encephalopathy, Overload, and Acidosis. Perform pharmacological audit (Metformin, ACEi/ARB, NSAIDs, SGLT2i, K-Sparing, Diuretics, Vit D, Iron).",
    "Neurology": "Focus on Cranial Nerves II-XII, motor strength (0-5), sensory deficits, reflexes (DTRs), and gait/coordination.",
    "Neurosurgery": "Focus on GCS score, intracranial pressure (ICP) concerns, and specific neurologic deficits relative to imaging.",
    "Nuclear Medicine": "Focus on tracer uptake, scan interpretations (PET/SPECT), and radioactive safety.",
    "Obstetrics and Gynecology": "Focus on Menstrual history (LMP), GTPAL, prenatal lab panels, and pelvic/speculum examination findings.",
    "Gynecologic Oncology": "Focus on tumor markers (CA-125), surgical staging, and chemotherapy response.",
    "Maternal-Fetal Medicine": "Focus on fetal monitoring, ultrasound findings (BPP/Growth), and high-risk maternal factors (Preeclampsia/GDM).",
    "Reproductive Endocrinology and Infertility": "Focus on follicle counts, hormone levels (FSH/AMH), and IVF cycle progress.",
    "Urogynecology": "Focus on pelvic floor support, POP-Q staging, and urodynamics.",
    "Oncology": "Focus on TNM staging, ECOG Performance Status, chemotherapy regimens, and treatment response/toxicity.",
    "Ophthalmology": "Focus on Visual Acuity (VA), Intraocular Pressure (IOP), extraocular movements, and fundus examination.",
    "Orthopedic Surgery": "Focus on joint Range of Motion (ROM), stability tests (e.g., Lachman), neurovascular status distal to injury, and imaging results.",
    "Otolaryngology": "Focus on Ear (otoscopy), Nose (septum/turbinates), and Throat (oropharynx/larynx) findings. Mention hearing status.",
    "Pathology": "Focus on histologic features, cytopathology, and immunohistochemistry (IHC) markers.",
    "Pediatrics": "Focus on growth charts (percentiles), developmental milestones, immunization status, and school performance.",
    "Pediatric Subspecialties": "Focus on age-appropriate manifestations of chronic pediatric conditions.",
    "Physical Medicine and Rehabilitation": "Focus on Functional status, mobility Aids, muscle tone (spasticity), and rehabilitation goals.",
    "Plastic and Reconstructive Surgery": "Focus on tissue viability, flap status, aesthetic symmetry, and scarring.",
    "Psychiatry": "Focus on Mental Status Exam (Appearance, Behavior, Speech, Mood, Affect, Thought Process/Content, Insight/Judgment).",
    "Pulmonology": "Focus on lung auscultation (wheeze/crackles/rhonchi), SpO2 on different environments (Air/Oxygen), and PFT findings.",
    "Radiology": "Focus on imaging findings (CT/MRI/X-ray), radiologic differentials, and interventional results.",
    "Radiation Oncology": "Focus on target volumes, dose fractionation, and radiation-induced side effects (skin/systemic).",
    "Rheumatology": "Focus on joint counts (tender/swollen), autoimmune markers (RF/ANA), and duration of morning stiffness.",
    "Sports Medicine": "Focus on sports-specific functional limitations and return-to-play criteria.",
    "Urology": "Focus on prostate exam (DRE), urinary stream characteristics, PSA levels, and renal stone status.",
    "Vascular Surgery": "Focus on peripheral pulses (DP/PT/Radial), ABI measurements, carotid bruits, and venous insufficiency findings."
}
